import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'baqrat-rouj',
    name: 'Baqrat Rouj',
    price: 4500,
    original_price: 6000,
    description: 'A luxurious and sophisticated fragrance with notes of saffron, jasmine, and amberwood. Inspired by the timeless elegance of high-end perfumery.',
    image: 'https://picsum.photos/seed/perfume1/800/800',
    images: ['https://picsum.photos/seed/perfume1/800/800'],
    notes: ['Saffron', 'Jasmine', 'Amberwood', 'Fir Resin'],
    usage: 'Perfect for evening wear and special occasions.',
    stock: 50,
    totalStock: 50,
    soldQuantity: 0,
    lowStockThreshold: 5,
    stockStatus: 'In Stock',
    featured: true,
    category: 'Unisex'
  },
  {
    id: 'caliber',
    name: 'Caliber',
    price: 3800,
    original_price: 5000,
    description: 'A bold and masculine scent for the modern man. Features a blend of citrus, spice, and deep woody undertones.',
    image: 'https://picsum.photos/seed/perfume2/800/800',
    images: ['https://picsum.photos/seed/perfume2/800/800'],
    notes: ['Bergamot', 'Black Pepper', 'Cedarwood', 'Vetiver'],
    usage: 'Ideal for office wear and professional settings.',
    stock: 40,
    totalStock: 40,
    soldQuantity: 0,
    lowStockThreshold: 5,
    stockStatus: 'In Stock',
    featured: true,
    category: 'Men'
  },
  {
    id: 'imperial-oud',
    name: 'Imperial Oud',
    price: 5500,
    original_price: 7500,
    description: 'Rich and woody, the essence of royalty. A deep, complex fragrance that celebrates the heritage of traditional oud.',
    image: 'https://picsum.photos/seed/perfume3/800/800',
    images: ['https://picsum.photos/seed/perfume3/800/800'],
    notes: ['Agarwood (Oud)', 'Sandalwood', 'Patchouli', 'Incense'],
    usage: 'Best suited for formal events and cold weather.',
    stock: 30,
    totalStock: 30,
    soldQuantity: 0,
    lowStockThreshold: 5,
    stockStatus: 'In Stock',
    featured: true,
    category: 'Unisex'
  },
  {
    id: 'white-oud',
    name: 'White Oud',
    price: 4200,
    original_price: 5500,
    description: 'A clean and elegant take on traditional oud. Light yet persistent, with a soft floral heart and a creamy base.',
    image: 'https://picsum.photos/seed/perfume4/800/800',
    images: ['https://picsum.photos/seed/perfume4/800/800'],
    notes: ['White Musk', 'Rose', 'Light Oud', 'Vanilla'],
    usage: 'A versatile fragrance for both day and night.',
    stock: 45,
    totalStock: 45,
    soldQuantity: 0,
    lowStockThreshold: 5,
    stockStatus: 'In Stock',
    featured: true,
    category: 'Unisex'
  },
  {
    id: 'deep-blue',
    name: 'Deep Blue',
    price: 3500,
    original_price: 4800,
    description: 'Refreshing and aquatic, perfect for daily wear. Captures the essence of the ocean breeze with a hint of citrus.',
    image: 'https://picsum.photos/seed/perfume5/800/800',
    images: ['https://picsum.photos/seed/perfume5/800/800'],
    notes: ['Sea Notes', 'Grapefruit', 'Rosemary', 'Amber'],
    usage: 'Great for casual outings and summer days.',
    stock: 60,
    totalStock: 60,
    soldQuantity: 0,
    lowStockThreshold: 5,
    stockStatus: 'In Stock',
    featured: true,
    category: 'Men'
  },
  {
    id: 'aliaf-100ml',
    name: 'Aliaf 100(ml)',
    price: 4000,
    original_price: 5200,
    description: 'A mysterious and captivating scent for the night. Deep, dark, and incredibly long-lasting.',
    image: 'https://picsum.photos/seed/perfume6/800/800',
    images: ['https://picsum.photos/seed/perfume6/800/800'],
    notes: ['Floral Notes', 'Amber', 'Woody Notes', 'Spices'],
    usage: 'Perfect for evening wear and special events.',
    stock: 35,
    totalStock: 35,
    soldQuantity: 0,
    lowStockThreshold: 5,
    stockStatus: 'In Stock',
    featured: true,
    category: 'Unisex'
  }
];

export const BRAND_NAME = 'Perfume Enclave';
export const BLUE_COLOR = '#1E3A8A';
